# Generated by Django 6.0.2 on 2026-05-27 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awareness', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('degenerative', 'Degenerative'), ('neurological', 'Neurological'), ('genetic', 'Genetic')], max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='BrainDisease',
        ),
        migrations.DeleteModel(
            name='ContactSubmission',
        ),
    ]
